### ISSUE TITLE
"wrong number of arguments" when terminated by Ctrl+C

### ISSUE THREAD

**Issue by voxik** [geemus/shindo#15]
I am trying to execute and interrupt the execution of excon testsuite and I receive this error:

```
$ shindo

  read should timeout
^C/usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:3:in `block in <top (required)>': wrong number of arguments (1 for 0) (ArgumentError)
    from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:65:in `call'
    from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:65:in `join'
    from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:65:in `run_in_thread'
    from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:72:in `<top (required)>'
    from /usr/share/gems/gems/shindo-0.3.8/bin/shindo:5:in `require_relative'
    from /usr/share/gems/gems/shindo-0.3.8/bin/shindo:5:in `<top (required)>'
    from /usr/bin/shindo:23:in `load'
```

Wouldn't be better to use proc instead of lambada on line [1] to avoid this issue?

[1] https://github.com/geemus/shindo/blob/master/lib/shindo/bin.rb#L3

**Comment by starbelly** [comment]
@geemus  I've recently experienced this bug or at least something similar. I was debugging code I was playing with in excon, and for that mater test units. I actually put a byebug statement in excon which ran fine exited normally the first round. However, shindo won't run again after that. It gets ready, and then hangs:

```ruby
$ shindo tests/errors_tests.rb

  HTTPStatusError request/response debugging
    new raises errors for bad URIs + returns true

^C/Users/bpaxton/.rvm/gems/ruby-2.3.0/gems/shindo-0.3.4/lib/shindo/bin.rb:3:in `block in <top (required)>': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/gems/shindo-0.3.4/lib/shindo/bin.rb:65:in `join'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/gems/shindo-0.3.4/lib/shindo/bin.rb:65:in `run_in_thread'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/gems/shindo-0.3.4/lib/shindo/bin.rb:72:in `<top (required)>'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/gems/shindo-0.3.4/bin/shindo:4:in `require'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/gems/shindo-0.3.4/bin/shindo:4:in `<top (required)>'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/bin/shindo:23:in `load'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/bin/shindo:23:in `<main>'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bpaxton/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

 It won't run again until I reboot. This appears to be because a ruby process is left hanging. 

```
~/devel/ruby/excon • ps -ef | grep ruby
  501   910     1   0 12:50PM ttys000    0:02.89 /Users/bpaxton/devel/ruby/excon/tests/servers/error.rb
```
 Killing that, allowed shindo to do it's thing again. 

 I can look further into this later and try to come up with a patch. It's an uncommon edge case I'm sure, but should probably still be fault tolerant in such a situation . You should be able to replicate this by putting a byebug call in Excon::Errors.status_error

**Comment by geemus** [comment]
Hmm. I haven't come across this, must be something to do with how it spins up things across threads (and the ctrl-c must then not join and then pointers are lost or something). Ruby threading has always been a bit awkward so far as I can tell, would be great to fix it but I'm not sure where to really start.
